### PR TITLE
Accept anything with Buffer Protocol, remove numpy

### LINKED ISSUE #99: Support for memoryview and PickleBuffer
As of 2.7.0rc1, cramjam seems to be incompatible with memoryview and PickleBuffer objects.
This is a blocker to the adoption in dask/distributed.

```python
>>> cramjam.bzip2.compress(memoryview(b"123"))
TypeError: argument 'data': failed to extract enum BytesType ('bytes | bytearray | File | Buffer | numpy')
- variant Bytes (bytes): TypeError: failed to extract field BytesType::Bytes.0, caused by TypeError: 'memoryview' object cannot be converted to 'PyBytes'
- variant ByteArray (bytearray): TypeError: failed to extract field BytesType::ByteArray.0, caused by TypeError: 'memoryview' object cannot be converted to 'PyByteArray'
- variant RustyFile (File): TypeError: failed to extract field BytesType::RustyFile.0, caused by TypeError: 'memoryview' object cannot be converted to 'File'
- variant RustyBuffer (Buffer): TypeError: failed to extract field BytesType::RustyBuffer.0, caused by TypeError: 'memoryview' object cannot be converted to 'Buffer'
- variant NumpyArray (numpy): TypeError: failed to extract field BytesType::NumpyArray.0, caused by TypeError: 'memoryview' object cannot be converted to 'PyArray<T, D>'

>>> import pickle, numpy
>>> a = numpy.ones(10)
>>> buffers = []
>>> pickle.dumps(a, buffer_callback=buffers.append)
>>> buffers
[<pickle.PickleBuffer at 0x7ff1f5b28540>]
>>> cramjam.bzip2.compress(buffers[0])
TypeError: argument 'data': failed to extract enum BytesType ('bytes | bytearray | File | Buffer | numpy')
- variant Bytes (bytes): TypeError: failed to extract field BytesType::Bytes.0, caused by TypeError: 'PickleBuffer' object cannot be converted to 'PyBytes'
- variant ByteArray (bytearray): TypeError: failed to extract field BytesType::ByteArray.0, caused by TypeError: 'PickleBuffer' object cannot be converted to 'PyByteArray'
- variant RustyFile (File): TypeError: failed to extract field BytesType::RustyFile.0, caused by TypeError: 'PickleBuffer' object cannot be converted to 'File'
- variant RustyBuffer (Buffer): TypeError: failed to extract field BytesType::RustyBuffer.0, caused by TypeError: 'PickleBuffer' object cannot be converted to 'Buffer'
- variant NumpyArray (numpy): TypeError: failed to extract field BytesType::NumpyArray.0, caused by TypeError: 'PickleBuffer' object cannot be converted to 'PyArray<T, D>'
```

### PR DESCRIPTION
**Pull request by milesgranger**
Will close #99 

- Adds support for anything which implements the buffer protocol
- As a result, removes need for numpy and PyBytes and PyByteArray implementations in BytesType variants

### CODE REVIEW

File: src/io.rs [hunk 1]
```diff
@@ -483,7 +403,7 @@ impl RustyBuffer {
 
         (*view).buf = bytes.as_ptr() as *mut std::os::raw::c_void;
         (*view).len = bytes.len() as isize;
-        (*view).readonly = 1;
+        (*view).readonly = 0;
```
Comment (crusaderky) [inline src/io.rs:406]: Interesting. Is this flag visible from Python? If it is, it was forcing a deep-copy upon deserialization; see:
https://github.com/dask/distributed/blob/4bd2ba7ec4e4a4669c13dc1e62820191664783f4/distributed/protocol/numpy.py#L137-L148

Comment (milesgranger) [reply src/io.rs:406]: Depends on the consumer of the buffer protocol. The consumer can choose to respect this (most likely) otherwise there is nothing truly stopping it from modifying the buffer. So likely, as seen there, if it needs to modify it, then it'll make a copy. I saw numpy defaults to allow it, so followed suit here and needed anyway as `cramjam.Buffer` can be passed in as before but now using the buffer protocol rather than the object itself.
